/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "T-Title": "#1A1A1AFF",
        "T-Body": "#444444FF",
        "T-Discription": "#666666FF",
        "T-PlaceHolder": "#99A1AFFF",
        "T-Disabled": "#A5A5A5FF",
        "T-Inverse": "#F3F3F3FF",
        "T-Primary": "#687AE6FF",
        "T-Link": "#FF8C19FF",
        "T-Link-Hover": "#20BE67FF",
        "T-Positive": "#009B98FF",
        "T-Attention": "#FF0000FF",
        "LG-Red1": "#A50034FF",
        "LG-Red2": "#FD312EFF",
        "LG-Red3": "#FF6F6FFF",
        "Primary": "#687AE6FF",
        "White": "#FFFFFFFF",
        "Icon-Gray": "#74818CFF",
        "Icon-Gray-State": "#C4CCD3FF",
        "Icon-Gray-Hover": "#212121FF",
        "Icon-Gray-Disable": "#A5A5A5FF",
        "Black": "#000000FF",
        "Bg1": "#F8F8F8FF",
        "Bg2": "#F2F3F7FF",
        "Bg3": "#F1F3FFFF",
        "Bg3-Deep": "#E0E5FFFF",
        "Bg4": "#E0E4E8FF",
        "Bg5": "#F1F7FFFF",
        "Form-Read-Dis-Bg": "#F4F4F4FF",
        "Form-Essen-Bg": "#FDFFE3FF",
        "Form-Input-Line": "#CCCCCCFF",
        "Divider-Content-Line": "#E0E0E0FF",
        "Divider-Top-Content-Line": "#D6D6D6FF",
        "Grid-Top-Line": "#212121FF",
        "Grid-Tr_Line": "#EAEAEAFF",
        "Grid-Header": "#F7F7F7FF",
        "Grid-Odd": "#FAFAFAFF",
        "Grid-Hover": "#FFF6DDFF",
        "Grid-Focus": "#EAFAFFFF",
        "Grid-Edit": "#FFE9A1FF",
        "Grid-Total": "#FEF2E0FF",
        "Form-Input-Line-Focus": "#212121FF",
        "Btn-Line-Focus": "#212121FF",
        "Btn-Line": "#AAAAAAFF",
        "Btn-Disable": "#D6DDEAFF",
        "Btn-Purple": "#687AE6FF",
        "Btn-Purple-Hover": "#9DA9F4FF",
        "Btn-Purple-Focus": "#2036BEFF",
        "Btn-Gray": "#4E6C84FF",
        "Btn-Gray-Hover": "#889BACFF",
        "Btn-Gray-Focus": "#123658FF",
        "Btn-White-Hover": "#F8F8F8FF",
        "Btn-Tab-Default": "#FFFFFFFF",
        "Ani1": "#687AE6FF",
        "Ani2": "#D867BFFF",
        "Ani3": "#9CA8FFFF"
      },
      spacing: {
        "Xsm": "6px",
        "Sm": "8px",
        "Md": "24px",
      },
      fontSize:{
        "H1": "32px",
        "H2": "24px",
        "H3": "20px",
        "B1": "18px",
        "B2": "16px",
        "B3": "14px",
        "B4": "12px",
      },
    }
  },
  plugins: [],
};
