/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "T-Title": "#1A1A1AFF",
        "T-Body": "#444444FF",
        "T-Discription": "#666666FF",
        "T-PlaceHolder": "#99A1AFFF",
        "T-Disabled": "#A5A5A5FF",
        "T-Inverse": "#F3F3F3FF",
        "T-Primary": "#687AE6FF",
        "T-Link": "#FF8C19FF",
        "T-Link-Hover": "#20BE67FF",
        "T-Positive": "#009B98FF",
        "T-Attention": "#FF0000FF",
        "LG-Red1": "#A50034FF",
        "LG-Red2": "#FD312EFF",
        "LG-Red3": "#FF6F6FFF",
        "Primary": "#687AE6FF",
        "White": "#FFFFFFFF",
        "Icon-Gray": "#74818CFF",
        "Icon-Gray-State": "#C4CCD3FF",
        "Icon-Gray-Hover": "#212121FF",
        "Icon-Gray-Disable": "#A5A5A5FF",
        "Black": "#000000FF",
        "Bg1": "#F8F8F8FF",
        "Bg2": "#F2F3F7FF",
        "Bg3": "#F1F3FFFF",
        "Bg3-Deep": "#E0E5FFFF",
        "Bg4": "#E0E4E8FF",
        "Bg5": "#F1F7FFFF",
        "Form-Read-Dis-Bg": "#F4F4F4FF",
        "Form-Essen-Bg": "#FDFFE3FF",
        "Form-Input-Line": "#CCCCCCFF",
        "Divider-Content-Line": "#E0E0E0FF",
        "Divider-Top-Content-Line": "#D6D6D6FF",
        "Grid-Top-Line": "#212121FF",
        "Grid-Tr_Line": "#EAEAEAFF",
        "Grid-Header": "#F7F7F7FF",
        "Grid-Odd": "#FAFAFAFF",
        "Grid-Hover": "#EBEBEBFF",
        "Grid-Focus": "#EAFAFFFF",
        "Grid-Edit": "#FFE9A1FF",
        "Grid-Total": "#FEF2E0FF",
        "Form-Input-Line-Focus": "#212121FF",
        "Btn-Line-Focus": "#212121FF",
        "Btn-Line": "#AAAAAAFF",
        "Btn-Disable": "#D6DDEAFF",
        "Btn-Purple": "#687AE6FF",
        "Btn-Purple-Hover": "#9DA9F4FF",
        "Btn-Purple-Focus": "#2036BEFF",
        "Btn-Gray": "#4E6C84FF",
        "Btn-Gray-Hover": "#889BACFF",
        "Btn-Gray-Focus": "#123658FF",
        "Btn-White-Hover": "#F8F8F8FF",
        "Btn-Tab-Default": "#FFFFFFFF",
      },
      spacing: {
        "Xsm": "6px",
        "Sm": "8px",
        "Md": "24px",
      },
      fontSize: {
        "da-h1": ["32px", { lineHeight: "100%", letterSpacing: "-0.64px" }],
        "da-h2": ["24px", { lineHeight: "150%", letterSpacing: "-0.48px" }],
        "da-h3": ["20px", { lineHeight: "150%", letterSpacing: "-0.4px" }],
        "da-b1": ["18px", { lineHeight: "150%", letterSpacing: "-0.36px" }],
        "da-b2": ["16px", { lineHeight: "150%", letterSpacing: "-0.32px" }],
        "da-b3": ["14px", { lineHeight: "150%", letterSpacing: "-0.28px" }],
        "da-b4": ["12px", { lineHeight: "150%", letterSpacing: "-0.24px" }],
      },
    }
  },
  plugins: [],
};
